"""empty message

Revision ID: fd680e6a4b97
Revises: b1a270cb10d9
Create Date: 2018-01-20 17:51:10.531583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd680e6a4b97'
down_revision = 'b1a270cb10d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'company', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_column('company', 'email')
    # ### end Alembic commands ###
